INSERT INTO PUBLIC.ACCOUNTS (ID, ACCOUNT_NUMBER, CURRENCY_CODE, AMOUNT, OWNER, ISBLOCKED) VALUES (1, '111', 'RUB', 425.5, 1, false) on conflict (id) do nothing;
INSERT INTO PUBLIC.ACCOUNTS (ID, ACCOUNT_NUMBER, CURRENCY_CODE, AMOUNT, OWNER, ISBLOCKED) VALUES (2, '222', 'RUB', 1000.5, 2, false) on conflict (id) do nothing;
INSERT INTO PUBLIC.ACCOUNTS (ID, ACCOUNT_NUMBER, CURRENCY_CODE, AMOUNT, OWNER, ISBLOCKED) VALUES (3, '333', 'RUB', 800, 3, false) on conflict (id) do nothing;
INSERT INTO PUBLIC.ACCOUNTS (ID, ACCOUNT_NUMBER, CURRENCY_CODE, AMOUNT, OWNER, ISBLOCKED) VALUES (4, '444', 'RUB', 425, 1, false) on conflict (id) do nothing;
INSERT INTO PUBLIC.ACCOUNTS (ID, ACCOUNT_NUMBER, CURRENCY_CODE, AMOUNT, OWNER, ISBLOCKED) VALUES (5, '555', 'RUB', 400, 2, false) on conflict (id) do nothing;
INSERT INTO PUBLIC.ACCOUNTS (ID, ACCOUNT_NUMBER, CURRENCY_CODE, AMOUNT, OWNER, ISBLOCKED) VALUES (6, '666', 'RUB', 950, 3, false) on conflict (id) do nothing;